#!/bin/bash

PERSON1=$1
PERSON2=$2

echo "$PERSON1: HI $PERSON2 , HOW ARE YOU"
echo "$PERSON2: I AM GOOD $PERSON1 WHAT ABOUT YOU"
echo "$PERSON1: WHAT ARE YOU DOING TODAY $PERSON2"
echo "$PERSON2: $PERSON1 I AM JUST PLANNING TO GO OUT WITH MY GIRLFRIEND"